ALTER TABLE loans 
ADD COLUMN IF NOT EXISTS "lateFeePercentage" NUMERIC DEFAULT 10,
ADD COLUMN IF NOT EXISTS "graceDays" INT DEFAULT 3;

ALTER TABLE loan_requests
ADD COLUMN IF NOT EXISTS "lateFeePercentage" NUMERIC DEFAULT 10,
ADD COLUMN IF NOT EXISTS "graceDays" INT DEFAULT 3;
