ALTER TABLE clients
ADD COLUMN IF NOT EXISTS "lastName" TEXT,
ADD COLUMN IF NOT EXISTS "documentType" TEXT DEFAULT 'Cedula',
ADD COLUMN IF NOT EXISTS "whatsapp" TEXT,
ADD COLUMN IF NOT EXISTS "province" TEXT,
ADD COLUMN IF NOT EXISTS "municipality" TEXT,
ADD COLUMN IF NOT EXISTS "sector" TEXT,
ADD COLUMN IF NOT EXISTS "referenceAddress" TEXT,
ADD COLUMN IF NOT EXISTS "companyName" TEXT,
ADD COLUMN IF NOT EXISTS "jobPosition" TEXT,
ADD COLUMN IF NOT EXISTS "coordinates" JSONB,
ADD COLUMN IF NOT EXISTS "routeId" UUID,
ADD COLUMN IF NOT EXISTS "routeSequence" INT DEFAULT 0;
